name: Test workflow

on:
  workflow_dispatch:
  push:
   branches:
    - main

jobs:
  job1:
   uses: MikeLydeamore/teleport/.github/workflows/workflow.yml@main
   with:
    target_repo: "MikeLydeamore/sandbox"
    target_path: "test"
    source_path: "test"
    token: ${{ secrets.PERSONAL_TOKEN }}